#!/bin/bash
##################################################################################
#                                                                                #
#  This script will call blj_config from ~/.bash_profile                         #
#  If profile exists: backup to ~/.bash_profile~, else create ~/.bash_profile.   #
#                                                                                #
##################################################################################
bashProfile=~/.bash_profile
bljDir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [ ! -f "$bashProfile" ]; then
	printf '%s\n' '#BioLockJ generated bash profile' > $bashProfile
	echo "    Created profile: $bashProfile"
else
	cp $bashProfile $bashProfile~
	echo "    Saved backup:  $bashProfile~"
fi

echo '[ -x "$bljDir/script/blj_config" ] && . $bljDir/script/blj_config' >> $bashProfile
source $bashProfile
echo "    Saved profile:  $bashProfile"
echo "BioLockJ installation complete!"