#!/bin/bash
##############################################################
##                                                          ##
##  This script is used for AWS core function + logic       ##
##                                                          ##
##############################################################
. $BLJ/script/aws_config_functions

# Remove all job-definitions 
aws_deregister_job_defs() {
	echo "CLEARING job-definitions..." 
	IFS=$'\t'
	vals=$(aws batch describe-job-definitions --status ACTIVE --query "jobDefinitions[*].jobDefinitionArn")
	[ ${#vals} -eq 0 ] && echo "No ACTIVE job-definitions found" && return
	echo "Remove Job defs: $vals"
	while [ ${#vals} -gt 0 ]; do
		module=$(aws_get_arn $vals) 
		echo "Found: ${module}"
		aws batch deregister-job-definition --job-definition ${module}
		status=ACTIVE
		while [ ${#status} -gt 0 ] && [ "$status" != "INACTIVE" ]; do
			sleep 10
			status=$(aws batch describe-job-definitions --job-definitions ${module} --query "jobDefinitions[*].status")
		done
		vals=${vals/${module}/""}
		echo "DE-RESISTERED: ${module}"
	done
	echo "All jobs de-registered (if possible)!"
	vals=$(aws batch describe-job-definitions)
	[ ${#vals} -eq 0 ] && echo "No Compute job-definitions remaining" && return
	echo "Remaining Job-Defs (none should be active):" && aws batch describe-job-definitions 
}

# Get 1st "arn*" value in list
# Param 1 list containing arn values
aws_get_arn() {
	module=
	i=1
	while [ ${#module} -eq 0 ] || [ "${module:0:1}" != "a" ]; do
		module=$(echo $1 | cut -f $i -d " ")
		((i++))
	done
	echo "$module"
}

# Remove all compute envs
aws_rm_compute_envs() {
	echo "CLEARING compute-environments..." 
	IFS=$'\t'
	vals=$(aws batch describe-compute-environments --query "computeEnvironments[*].computeEnvironmentArn")
	[ ${#vals} -eq 0 ] && echo "No compute-environments found" && return
	echo "Remove Compute Envs: $vals"
	while [ ${#vals} -gt 0 ]; do
		module="$(aws_get_arn $vals)"
		echo "REMOVE: $module"
		vals=${vals/$module/""}
		statusReason=$(aws batch describe-compute-environments --compute-environment $module --query "computeEnvironments[*].statusReason")
		if [ ${#statusReason} -gt 0 ] && [ "$statusReason" != "${statusReason/'Access denied'}" ]; then
			status=$(aws batch describe-compute-environments --compute-environment $module --query "computeEnvironments[*].state")
			[ "$status" != "DISABLED" ] && aws batch update-compute-environment --compute-environment $module --state DISABLED
			while [ ${#status} -gt 0 ] && [ "$status" != "DISABLED" ]; do
				sleep 10
				status=$(aws batch describe-compute-environments --compute-environment $module --query "computeEnvironments[*].state")
			done
			echo "DISABLED: $module"
			aws batch delete-compute-environment --compute-environment $module
			echo "DELETED: $module"
		else
			echo "Skipping:  $statusReason" 
		fi
	done
	echo "All Compute Envs removed (if possible)!"
	vals=$(aws batch describe-compute-environments)
	[ ${#vals} -eq 0 ] && echo "No compute-environments  remaining" && return
	echo "Remaining compute-environments:" && aws batch describe-compute-environments
}

# Remove AWS Job Queues
aws_rm_job_queues() {
	IFS=$'\t'
	vals=$(aws batch describe-job-queues --query "jobQueues[*].jobQueueArn")
	[ ${#vals} -eq 0 ] && echo "No job-queues found" && return
	echo "Remove Job Queues: $vals"
	while [ $vals -gt 0 ]; do
		module=$(aws_get_arn $vals) 
		echo "REMOVE: $module"
		status=$(aws batch describe-job-queues --job-queue $module --query "jobQueues[*].status")
		[ "$status" == "DISABLED" ] && aws batch update-job-queue --job-queue $module --status DISABLED
		while [ ${#status} -gt 0 ] && [ "$status" != "DISABLED" ]; do
			sleep 10
			status=$(aws batch describe-job-queues --job-queue $module --query "jobQueues[*].status")
		done
		echo "DISABLED: $module"
		vals=${vals/$module/""}
		aws batch delete-job-queue --job-queue $module
		echo "DELETED: $module"
	done
	echo "All Job Queues removed (if possible)!"
	vals=$(aws batch describe-job-queues )
	[ ${#vals} -eq 0 ] && echo "No Job Queues remaining" && return
	echo "Remaining Job Queues:" && aws batch describe-job-queues
}

# De-register, disable, and remove AWS batch objects
aws_clear_skies() {
 	kill_head_node
	aws_deregister_job_defs
	aws_rm_job_queues
	aws_rm_stacks
	aws_rm_compute_envs
	aws_rm_s3_buckets
	aws_rm_key_pairs
}

# Remove AWS key_pairs + keyPair file
aws_rm_key_pairs() {
	echo "CLEARING Key-Pairs..." 
	IFS=$'\t'
	vals=$(aws ec2 describe-key-pairs --query "KeyPairs[*].KeyName")
	[ ${#vals} -eq 0 ] && echo "No keys found" && return
	while [ ${#vals} -gt 0 ]; do
		module=$(echo $vals | cut -f 1 -d " ")
		aws ec2 delete-key-pair --key-name $module
		vals=${vals/$module/""}
		echo "DELETED: $module"
	done
	echo "All Key-Pairs on AWS Cloud deleted (if possible)!"
	[ ${#key_file} -gt 0 ] && rm -rf $(key_file)
	echo "All Key-Pair files deployed locally are deleted (if possible)!"
	vals=$(aws ec2 describe-key-pairs)
	[ ${#vals} -eq 0 ] && echo "No Key-Pairs remaining" && return
	echo "Remaining Key-Pairs:" && aws ec2 describe-key-pairs
}

# Remove S3 buckets
aws_rm_s3_buckets() {
	echo "CLEARING S3 buckets..." 
	s3Buckets=$(aws s3api list-buckets --query "Buckets[*].Name")
	buckets=("$s3Buckets")
	for bucket in ${buckets[@]}; do
		echo "Found bucket: $bucket"
		aws s3api delete-bucket --bucket $bucket
		echo "REMOVED bucket: $bucket"
	done
	s3Buckets=$(aws s3api list-buckets)
	[ ${#s3Buckets} -eq 0 ] && echo "No S3 buckets remaining" && return
	echo "Remaining S3 buckets:"  && aws s3api list-buckets
	
}

aws_rm_stacks() {
	echo "CLEARING cloudformation stacks..." 
	IFS=$'\t'
	vals=$(aws cloudformation describe-stacks --query "Stacks[*].StackId")
	[ ${#vals} -eq 0 ] || [ "$vals" == "None" ] && echo "No stacks found" && return
	while [ ${#vals} -gt 0 ]; do
		module=$(aws_get_arn $vals) 
		status=$(aws cloudformation describe-stacks --stack-name $module --query "Stacks[*].StackStatus")
		[ "$status" == "DELETE_COMPLETE" ] && "$module=DELETE_COMPLETE" && continue
		echo "Found: $module"
		aws cloudformation delete-stack --stack-name $module 
		status=ACTIVE
		while [ "$status" != "DELETE_COMPLETE" ]; do
			sleep 10
			status=$(aws cloudformation describe-stacks --stack-name $module --query "Stacks[*].StackStatus")
		done
		vals=${vals/$module/""}
		echo "DELETED: $module"
	done
	
	echo "All Stacks deleted (if possible)!"
	stacks=$(aws cloudformation describe-stacks)
	[ ${#stacks} -eq 0 ] && echo "No cloudformation stacks remaining" && return
	echo "Remaining DELETE_COMPLETE Stacks:" && aws cloudformation list-stacks
}

# Amazon EC2 deletes all EBS volumes that were attached when the instance launched. 
kill_head_node() {
	echo "CLEARING ec2 instances..." 
	instances=$(aws ec2 describe-instances)
	[ ${#instances} -eq 0 ] && echo "No ec2 instances remaining" && return

	aws ec2 stop-instances --instance-ids $(get_blj_prop instanceID)
	aws ec2 terminate-instances --instance-id $(get_blj_prop instanceID)
	instances=$(aws ec2 describe-instances)
	[ ${#instances} -eq 0 ] && echo "No ec2 instances remaining" && return
	echo "Remaining ec2 instances:" && aws ec2 describe-instances
}
