#!/bin/bash
#########################################################################
##                                                                     ##
##  This script fetches the latest BioLockJ code from GitHub.          ##
##  Set $BLJ file permissions to 770 with group owner $BLJ_GRP_OWNER.  ##
##  Build the latest BioLockJ.jar file to $BLJ/dist                    ##
##                                                                     ##
#########################################################################

# Returns Y or N to indicate if directory exists
function valid_dir {
	if [ ${#1} -gt 0 ] && [ -d "$1" ]; then  
		echo "Y" 
	else 
		echo "N"
	fi
}

echo "Pull latest BioLockJ code from GitHub"
if [ "$(valid_dir $BLJ)" == "Y" ]; then
	cd $BLJ
	git pull
	echo "Git pull Successful"
else
	echo "Invalid directory path: $BLJ" && exit 1
fi

blj_build standard-build
chmod -R 770 $BLJ
[ ${#BLJ_GRP_OWNER} -gt 0 ] && chown -R :$BLJ_GRP_OWNER $BLJ && echo "Set $BLJ group owner to $BLJ_GRP_OWNER"
