#!/bin/bash
###################################################################
##                                                               ##
##  Functions for BioLockJ developers.                           ##
##                                                               ##
###################################################################



# ---> should be removed
# Call ANT to build BioLockJ
blj_build() {
	console_log "Building BioLockJ with ANT..."
	[ ! -f "$BLJ/resources/build.xml" ] && console_log "Error [ blj_functions.blj_build() ]: ANT build script missing: $BLJ/resources/build.xml" && return
	myDir="$PWD"
	cd $BLJ/resources
	[ ${#1} -eq 0 ] && ant
	[ ${#1} -gt 0 ] && ant $1
	console_log "Ant script execution complete"

	if [ -f "$BLJ/dist/BioLockJ.jar" ]; then
		ls -lh "$BLJ/dist/BioLockJ.jar"
	else
		console_log "Build Failed - missing $BLJ/dist/BioLockJ.jar"
	fi
	cd $myDir
}

# ---> should be removed
# Pull the latest Git code and build BioLockJ.jar
blj_deploy() {
	blj_sup_git
	blj_git
	blj_build build-jar
}

# ---> should be removed
# Git latest $BLJ + build BioLockJ.jar
blj_git() {
	[ ! -d "${BLJ}" ] && console_log "Cannot build BLJ: directory not found: ${BLJ}" && return
	blj_git_reset "${BLJ}"
}

# ---> should be removed
# Reset git repo + set file permissions 770
# Param 1 - Directory path of Git repo (use current directory if undefined)
blj_git_reset() {
	gitDir="$PWD" && [ ${#1} -gt 0 ] && gitDir="${1}" 
	echo "Get latest code from GitHub repo: ${gitDir}" && cd "${gitDir}"
	git fetch && git checkout -q master && git reset -q --hard origin/master  
	chmod -R 770 "${gitDir}"
	echo "$SPACER"
	echo "${gitDir} Git pull SUCESSFULLY COMPLETED!"
	chmod -R 770 "${gitDir}"
	echo "${gitDir} permissions set: 770"
	echo "$SPACER"
	echo "" && cd "${gitDir}"
}


# Git latest ${BLJ_SUP}
blj_sup_git() {
	[ ! -d "${BLJ_SUP}" ] && echo "Cannot build BLJ_SUP: directory not found: ${BLJ_SUP}" && return
	blj_git_reset "${BLJ_SUP}"
}

