#!/bin/bash
###############################################################################
##                                                                           ##
##  This script manually completes current module and pipeline status.       ##
##                                                                           ##
###############################################################################

parentDir="$(dirname $PWD)"
currentDir="$(basename $PWD)"

if $(is_pipeline_dir $currentDir); then
	parentDir=$currentDir
elif ! $(is_pipeline_dir $parentDir); then 
	echo "ABORT: blj_complete must be executed from a pipeline module directory" && exit 1
fi

pipelineDir=$(current_pipeline)

echo "Update $pipelineDir status to: COMPLETE"
[ ! -f "$pipelineDir/biolockjComplete" ] && touch "$pipelineDir/biolockjComplete" && echo "created $pipelineDir/biolockjComplete"
[ -f "$pipelineDir/biolockjFailed" ] && rm "$pipelineDir/biolockjFailed" && echo "removed $pipelineDir/biolockjFailed"


for modDir in $pipelineDir/*; do
	if $(is_module_dir "$modDir"); then
		[ -f "$modDir/biolockjStarted" ] && rm "$modDir/biolockjStarted" && echo "deleted $modDir/biolockjStarted"
		[ ! -f "$modDir/biolockjComplete" ] && touch "$modDir/biolockjComplete" && echo "created $modDir/biolockjComplete"
	fi
done
