#!/bin/bash
###########################################################################
##                                                                       ##
##  This script tails 1K lines from the current pipelines Java log file. ##
##  If the current directory is not a BioLockJ pipeline, print last 1K   ##
##  lines from the most recent pipeline executed.  If param is passed,   ##
##  pass it to tail command in place of -1000 parameter.                 ##
##                                                                       ##
###########################################################################
. $BLJ/script/blj_functions

pipeline=$(current_pipeline)
if [ ${#pipeline} -gt 0 ]; then
	echo "Tail current BioLockJ pipeline log: $pipeline"
else
	pipeline=$(most_recent_pipeline)
	[ ${#pipeline} -gt 0 ] && echo "Tail most recent BioLockJ pipeline log: $pipeline"
fi

if [ ${#pipeline} -gt 0 ]; then
	if [ ${#1} -gt 0 ]; then
		\tail $1 $pipeline/*.log 
	else
		\tail 1000 $pipeline/*.log 
	fi
else
	echo "No pipelines found in BLJ_PROJ: $BLJ_PROJ"
fi
