#!/bin/bash
##############################################################
##                                                          ##
##  This script navigates the $USER to their most recent    ##
##  pipeline and lists the current directory                ##
##                                                          ##
##############################################################

[ ! -d "$BLJ_PROJ" ] && echo "Exit program - Required env variable BLJ_PROJ undefined" && exit 1

pipeline=$(most_recent_pipeline)
if [ ${#pipeline} -gt 0 ]; then
	echo "Goto latest BioLockJ pipeline: $pipeline"
	cd "$pipeline"
	ls "$pipeline"
else
	echo "No pipelines found in BLJ_PROJ: $BLJ_PROJ"
fi