#!/bin/bash
###############################################################################
##                                                                           ##
##  This script manually completes current module and pipeline status.       ##
##                                                                           ##
###############################################################################
. $BLJ/script/blj_functions

parentDir="$(dirname $PWD)"
currentDir="$(basename $PWD)"

if $(is_pipeline_dir $currentDir); then
	parentDir=$currentDir
elif ! $(is_pipeline_dir $parentDir); then 
	echo "ABORT: blj_complete must be executed from a pipeline directory" && exit 1
fi

echo "Update $parentDir status to: COMPLETE"
[ ! -f "$parentDir/biolockjComplete" ] && touch "$parentDir/biolockjComplete" && echo "created $parentDir/biolockjComplete"
[ -f "$parentDir/biolockjFailed" ] && rm "$parentDir/biolockjFailed" && echo "removed $parentDir/biolockjFailed"


for modDir in $parentDir/*; do
	if [ -d "$modDir" ]; then
		[ -f "$modDir/biolockjStarted" ] && rm "$modDir/biolockjStarted" && echo "deleted $modDir/biolockjStarted"
		[ ! -f "$modDir/biolockjComplete" ] && touch "$modDir/biolockjComplete" && echo "created $modDir/biolockjComplete"
	fi
done
