#!/bin/bash
###########################################################################
##                                                                       ##
##  This script tails 1K lines from the current pipelines Java log file. ##
##  If the current directory is not a BioLockJ pipeline, print the       ##
##  tail 1K lines from the most recent pipeline executed.                ##
##                                                                       ##
###########################################################################
. $BLJ/script/blj_functions

pipeline=$(current_pipeline)
if [ ${#pipeline} -gt 0 ]; then
	echo "Tail current BioLockJ pipeline log: $pipeline"
else
	pipeline=$(most_recent_pipeline)
	[ ${#pipeline} -gt 0 ] && echo "Tail most recent BioLockJ pipeline log: $pipeline"
fi

if [ ${#pipeline} -gt 0 ]; then
	\tail -1000f $pipeline/*.log 
else
	echo "No pipelines found in BLJ_PROJ: $BLJ_PROJ"
fi
