#!/bin/bash
#################################################################
##                                                             ##
##  This script calls ant on build.xml to create BioLockJ.jar  ##
##                                                             ##
#################################################################
. $BLJ/script/blj_functions

echo "Building BioLockJ with ANT..."
if $(valid_dir $BLJ/resources); then
	cd $BLJ/resources
	[ ${#1} -eq 0 ] && ant
	[ ${#1} -gt 0 ] && ant $1
	echo "Ant script execution complete"
else
	echo "Invalid directory path: $BLJ/resources" && exit 1
fi

if $(valid_file $BLJ/dist/BioLockJ.jar); then
	ls $BLJ/dist/BioLockJ.jar
else
	echo "Build Failed - missing $BLJ/dist/BioLockJ.jar"
fi
