#!/bin/bash
#################################################################
##                                                             ##
##  This script calls ant on build.xml to create BioLockJ.jar  ##
##                                                             ##
#################################################################
function valid_dir {
	if [ ${#1} -gt 0 ] && [ -d "$1" ]; then  
		echo "Y" 
	else 
		echo "N"
	fi
}

# Returns Y or N to indicate if file exists
function valid_file {
	if [ ${#1} -gt 0 ] && [ -f "$1" ]; then  
		echo "Y" 
	else 
		echo "N"
	fi
}

echo "Building BioLockJ..."
if [ "$(valid_dir $BLJ/resources)" == "Y" ]; then
	cd $BLJ/resources
	[ ${#1} -eq 0 ] && ant
	[ ${#1} -gt 0 ] && ant $1
	echo "Ant script execution complete"
else
	echo "Invalid directory path: $BLJ/resources"
fi

if [ "$(valid_file $BLJ/dist/BioLockJ.jar)" == "Y" ]; then
	echo "Build Successful - created $BLJ/dist/BioLockJ.jar"
else
	echo "Build Failed - missing $BLJ/dist/BioLockJ.jar"
fi