#!/bin/bash
#################################################################
##                                                             ##
##  This script calls ant on build.xml to create BioLockJ.jar  ##
##                                                             ##
#################################################################

echo "Building BioLockJ with ANT..."
[ ! -f "$BLJ/resources/build.xml" ] && echo "ANT build script missing: $BLJ/resources/build.xml" && exit 1

cd $BLJ/resources
[ ${#1} -eq 0 ] && ant
[ ${#1} -gt 0 ] && ant $1
echo "Ant script execution complete"

if [ -f "$BLJ/dist/BioLockJ.jar" ]; then
	ls -lh "$BLJ/dist/BioLockJ.jar"
else
	echo "Build Failed - missing $BLJ/dist/BioLockJ.jar"
fi
