#!/bin/bash
##############################################################
##                                                          ##
##  This script navigates the $USER to their most recent    ##
##  pipeline and lists the current directory                ##
##                                                          ##
##############################################################
. $BLJ/script/blj_functions

pipeline=$(most_recent_pipeline)
if [ ${#pipeline} -gt 0 ]; then
	echo "Goto latest BioLockJ pipeline: $pipeline"
	cd "$pipeline"
	ls "$pipeline"
elif $(valid_dir $BLJ_PROJ); then
	cd $BLJ_PROJ
	echo "No pipelines found in BLJ_PROJ: $BLJ_PROJ"
else
	echo "BLJ_PROJ is not a valid directory: $BLJ_PROJ"
fi