#!/bin/bash
###############################################################################
##                                                                           ##
##  This script manually resets current module and pipeline status.          ##
##  All modules numbered higher than the current module will also be reset.  ##
##                                                                           ##
###############################################################################
. $BLJ/script/blj_functions

parentDir="$(dirname $PWD)"
currentDir="$(basename $PWD)"
targetNum=${currentDir%_*}

! $(is_pipeline_dir $parentDir) || (($targetNum < 0)) || [ ! -f "$PWD/biolockjComplete" ] && \
	echo "ABORT: blj_reset must be executed within a biolockjComplete module directory" && exit 1

echo "Reset $parentDir modules after and including step #$targetNum"
[ -f "$parentDir/biolockjComplete" ] && rm "$parentDir/biolockjComplete" && echo "deleted $parentDir/biolockjComplete"
[ ! -f "$PWD/biolockjStarted" ] && touch "$PWD/biolockjStarted" && echo "created $PWD/biolockjStarted"
rm "$PWD/biolockjComplete" && echo "deleted $PWD/biolockjComplete"

for modDir in $parentDir/*; do
	if [ -d $modDir ]; then
		dirName="$(basename $modDir)"
		modNum=${dirName%_*}
		if [ $modNum -gt $targetNum ] && ! $(is_empty $modDir); then
			[ -f "$modDir/biolockjComplete" ] && rm "$modDir/biolockjComplete" && echo "deleted $modDir/biolockjComplete"
			[ ! -f "$modDir/biolockjStarted" ] && touch "$modDir/biolockjStarted" && echo "created $modDir/biolockjStarted"
		fi
	fi
done
