#!/bin/bash
###########################################################################
##                                                                       ##
##  Pull all Docker hub images                                           ##
##                                                                       ##
###########################################################################

docker pull biolockj/manager
docker pull biolockj/javamodule
docker pull biolockj/awkfastaconverter
docker pull biolockj/pearmergereads
docker pull biolockj/rdpclassifier
docker pull biolockj/qiimeclassifier
docker pull biolockj/krakenclassifier
docker pull biolockj/metaphlanclassifier
docker pull biolockj/r_module
echo "Docker pull complete!"