#!/bin/bash
###########################################################################
##                                                                       ##
##  Build all Docker images                                              ##
##                                                                       ##
###########################################################################

# Returns Y or N to indicate if directory exists
function valid_dir {
	if [ ${#1} -gt 0 ] && [ -d "$1" ]; then  
		echo "Y" 
	else 
		echo "N"
	fi
}

BLJ_VERSION=biolockj_v1.0
DOCKER_CLIENT=docker-18.06.0-ce.tgz

if [ "$(valid_dir $BLJ/resources/docker)" == "Y" ]; then
	
	echo "Build new module images..."
	docker build --build-arg BLJ_DATE=$(date +%s) --build-arg BLJ_VERSION=$BLJ_VERSION --build-arg DOCKER_CLIENT=$DOCKER_CLIENT -t biolockj/manager $BLJ/resources/docker
	docker build --build-arg BLJ_DATE=$(date +%s) --build-arg BLJ_VERSION=$BLJ_VERSION -t biolockj/javamodule $BLJ/resources/docker/JavaModule
	docker build -t biolockj/awkfastaconverter $BLJ/resources/docker/seq/AwkFastaConverter
	docker build -t biolockj/pearmergereads $BLJ/resources/docker/seq/PearMergeReads
	docker build -t biolockj/rdpclassifier $BLJ/resources/docker/classifier/r16s/RdpClassifier
	docker build -t biolockj/qiimeclassifier $BLJ/resources/docker/classifier/r16s/QiimeClassifier
	docker build -t biolockj/krakenclassifier $BLJ/resources/docker/classifier/wgs/KrakenClassifier
	docker build -t biolockj/metaphlanclassifier $BLJ/resources/docker/classifier/wgs/MetaphlanClassifier
	docker build -t biolockj/r_module $BLJ/resources/docker/R_Module

	echo "Deployment complete!"

else
	echo "Invalid directory path: $BLJ/resources/docker"
fi
