#!/bin/bash
###########################################################################
##                                                                       ##
##  Push all Docker images to Docker hub                                 ##
##                                                                       ##
###########################################################################

docker push biolockj/manager
docker push biolockj/javamodule
docker push biolockj/awkfastaconverter
docker push biolockj/pearmergereads
docker push biolockj/rdpclassifier
docker push biolockj/qiimeclassifier
docker push biolockj/krakenclassifier
docker push biolockj/metaphlanclassifier
docker push biolockj/r_module
echo "Docker push complete!"