#!/bin/bash
###########################################################################
##                                                                       ##
##  Build all Docker images and push them to the Docker hub              ##
##                                                                       ##
###########################################################################

# Returns Y or N to indicate if directory exists
function valid_dir {
	if [ ${#1} -gt 0 ] && [ -d "$1" ]; then  
		echo "Y" 
	else 
		echo "N"
	fi
}

# Remove old Docker images
function clearDock {
	echo "Stop/remove all containers & remove old images..."
	docker kill $(docker ps -q)
	docker rm $(docker ps -aq)
	docker rmi $(docker images -f "dangling=true" -q) 
	echo "Verify all containers & old images are removed..."
	docker images
	docker container ls --all
}

if [ "$(valid_dir $BLJ/resources/docker)" == "Y" ]; then
	docker_build
	clearDock
	docker_push
else
	echo "Invalid directory path: $BLJ/resources/docker"
fi
