#!/bin/bash
##################################################################################
##                                                                              ##
##  Script launches BioLockJ via Docker + creates $DOCKER_CLONE_SCRIPT          ##
##                                                                              ##
##  Bash env must include pipeline base directory: ${BLJ_PROJ}                  ##
##                                                                              ##
##  Required Parameters:                                                        ##
##  Config file path:       -c                                                  ##
##  Input directory:        -i <path>                                           ##
##                                                                              ##
##  Optional Parameters:                                                        ##
##  Aws flag:               -aws                                                ##
##  Run GUI flag:           -gui                                                ##
##  Metadata directory:     -m  <path>                                          ##
##  New email password:     -p  <new_pass>                                      ##
##  Restart flag:           -r  <directory>                                     ##
##                                                                              ##
##################################################################################
. "${DOCKER_LIB}"

cmd="dockblj ${@}"
printf "\n---------> Execute CMD [  ${cmd}  ] \n\n"
[ ${#DOCKER_ID} -eq 0 ] && exit_script "Error [ dockblj ]: Required bash variable DOCKER_ID undefined"
[ ! -d "${BLJ_PROJ}" ] && exit_script "Error [ dockblj ]: Required bash variable BLJ_PROJ undefined"

# Populate docker run env variable $BLJ_OPTIONS 
# Always include vars to map Host paths: Config, $BLJ_PROJ, and $HOME.
# In AWS mode, add -aws indicator, otherwise include the Host path for pipeline input. 
# These paths are used by biolockj_controller to map Docker volumes for java_module containers
blj_options() {
	options="-u ${HOME} -b $(blj_proj)" 
	$(has_param $runDev) && $(has_param $HOST_BLJ) && options="${options} --blj ${HOST_BLJ}"
	$(has_param $runDev) && $(has_param $HOST_BLJ_SUP) && options="${options} --bljSup ${HOST_BLJ_SUP}"
	$(has_param $launchGui) && echo ${options} && return
	
	$(has_param $doRestart) && options="${options} -r ${BLJ_PROJ}/${doRestart#$(blj_proj)/}"
	$(has_param $newPass) && options="${options} -p $newPass"
	$(has_param $metaPath) && options="${options} -m $metaPath"
	echo ${options} -i ${inputDir} -c ${config} ${runAws}
}

# Return $HOST_BLJ_PROJ if called from within the biolockj_controller Docker container, otherwise return $BLJ_PROJ
# If dir ends with "/" trim it off
blj_proj() {
	if [ -d "${HOST_BLJ_PROJ}" ]; then bljProj="${HOST_BLJ_PROJ}"; else bljProj="${BLJ_PROJ}"; fi
	if [ "${bljProj: -1}" == "/" ]; then
		len=$((${#bljProj}-1))
		bljProj="${bljProj:0:len}"
	fi
	! $(has_param $bljProj) && exit_script "Error [ dockblj.blj_proj ]: Required env variable BLJ_PROJ undefined"
	echo "${bljProj}"
	
}

# Build a script that can be used to launch a clone of the
# Param 1 - Full Docker run command
build_clone_script() {
	echo "#!/bin/bash" > "${DOCKER_CLONE_SCRIPT}"
	echo "# This script launches a clone of the last biolockj_controller (same env vars + volumes)" >> "${DOCKER_CLONE_SCRIPT}"
	echo ${@/$(get_docker_img)/-ti $(dock_id)/biolockj_controller /bin/bash} >> "${DOCKER_CLONE_SCRIPT}"
	chmod 777 "${DOCKER_CLONE_SCRIPT}"
	echo "** DEVELOPER NOTE ** dockblj creates a script that if run, launchs a clone of this container shell (same env vars + volumes) without executing the default CMD"
	echo "** DEVELOPER NOTE ** Useful to inspect moduleruntime envionment.  A shortcut to run the script is provided via the \"dclone\" alias"
	echo "even after this container is terminated --> ${DOCKER_CLONE_SCRIPT}"
	[ -f "${DOCKER_CLONE_SCRIPT}" ] && cat "${DOCKER_CLONE_SCRIPT}" & printf "\n"
}

# Get Docker image - add port, entrypoint, anc command if launching GUI
get_docker_img() {
	cmd=$(dock_id)/biolockj_controller	
	$(has_param $launchGui) && echo "-p 8080:3000 --expose 8080 -w '$BLJ/web_app' --entrypoint '/bin/bash' ${cmd} -c 'npm start'"
	! $(has_param $launchGui) && echo "${cmd}"
}

# Get mapped  Docker volumes
get_volumes() {
	vols="-v ${DOCK_SOCK}:${DOCK_SOCK} -v ${HOME}:${BLJ_HOST_HOME}"
	if $(has_param $runAws); then
		vols="${vols} -v ${EFS}:${EFS}:delegated"
	else
		vols="${vols} -v $(blj_proj):${EFS_PROJ}:delegated"
		if $(has_param $launchGui) && [ -d "${BLJ}/resources/config/gui" ]; then
			vols="${vols} -v ${BLJ_CONFIG}:${BLJ}/resources/config/gui"
		else
			vols="${vols} -v $inputDir:${BLJ_INPUT}:ro -v $(dirname $config):${BLJ_CONFIG}:ro"
			$(has_param $metaPath) && vols="${vols} -v $metaPath:${BLJ_META}:ro"
		fi
	
		$(has_param $runDev) && $(has_param $HOST_BLJ) && vols="${vols} -v ${HOST_BLJ}:/app/biolockj:ro"
		$(has_param $runDev) && $(has_param $HOST_BLJ_SUP) && vols="${vols} -v ${HOST_BLJ_SUP}:/app/blj_support:ro"
	fi
	echo "${vols}"
}

# Boolean evaluation if single argument passed exists with a non-zero size
# Param 1 - Script arg
has_param() {
	[ ${#1} -gt 0 ]
}

# Print and execute the docker run command with the correct volumes and env variables
run_docker() {
	cmd="docker run --rm -e \"BLJ_OPTIONS=$(blj_options)\" $(get_volumes) $(get_docker_img)"
	printf "\n---------> Execute CMD [  ${cmd}  ] \n\n"
	build_clone_script "${cmd}"
	docker run --rm -e "BLJ_OPTIONS=$(blj_options)" $(get_volumes) "$(get_docker_img)"
}

# Start the local browswer
startBrowser() {
	sleep 2
	# Helpful info: https://stackoverflow.com/questions/3124556/clean-way-to-launch-the-web-browser-from-shell-script#3124750
	if which xdg-open > /dev/null; then
		xdg-open 'http://localhost:8080/'
	elif which gnome-open > /dev/null; then
		gnome-open 'http://localhost:8080/'
	elif which python > /dev/null; then
		python -mwebbrowser http://localhost:8080/
	else
		echo "Web browser not found on localhost!"
	fi
}

# Verify host directory exists, if dockblj is not deployed inside a Docker container
verify_host_dir() {
	#echo "validate Host Dir: $# + $1"
 	[ $# -eq 2 ] && [ ! -d "${1}" ] && exit_script "Error [ dockblj ]: $2 directory not found: $1"
}

# Verify host file exists, if dockblj is not deployed inside a Docker container
verify_host_file() {
	#echo "validate Host Dir: $# + $1"
	[ $# -eq 2 ] && [ ! -f "${1}" ] && exit_script "Error [ dockblj ]: $2 file not found: $1"
}

# Verify paths are valid, if dockblj is not run inside a Docker container
verify_inputs() {
	$(has_param $doRestart) && verify_host_dir $doRestart Restart
	$(has_param $config) && verify_host_file $config Config
	$(has_param $metaPath) && verify_host_dir $metaPath Metadata
	! $(has_param $inputDir) && exit_script "Error [ dockblj ]: The -i parameter must reference a single input directory"
	dirPath=( ${inputDir//, } )
	[ ${#dirPath[@]} -gt 1 ] && exit_script "Error [ dockblj ]: The -i parameter must reference a single input directory"
	verify_host_dir $dirPath Input
}

launchGui=$(arg_exists "$@" -gui)
runAws=$(arg_exists "$@" -aws)
runDev=$(arg_exists "$@" -dev)
config=$(named_arg "$@" -c)
inputDir=$(named_arg "$@" -i)
metaPath=$(named_arg "$@" -m)
newPass=$(named_arg "$@" -p)
doRestart=$(named_arg "$@" -r)

if $(has_param $runDev); then
	echo "Run DEV mode!"
	[ ${#HOST_BLJ} -eq 0 ] && [ -d "${BLJ}" ] && HOST_BLJ="${BLJ}" 
	[ ${#HOST_BLJ_SUP} -eq 0 ] && [ -d "${BLJ_SUP}" ] && HOST_BLJ_SUP="${BLJ_SUP}" 
fi

! $(has_param $launchGui) && verify_inputs 
run_docker
$(has_param $launchGui) && startBrowser
