#!/bin/bash
###############################################################################
##                                                                           ##
##  BioLockJ returns variables defined in the runtime shell environment.     ##
##                                                                           ##
###############################################################################
. $BLJ/script/blj_functions

[ $#2 -eq 2 ] && user_profile="${2}"
[ ! -f "${user_profile}" ] && user_profile="$(get_default_profile)"
[ -f "${user_profile}" ] && source "${user_profile}"
echo BLJ_GET_ENV_VAR $(eval "echo ${1}")
