#!/bin/bash
################################################################################
##  Build Nexflow main.nf template                                            ##
##  Query for SEARCH_KEY in all java files under $BLJ/src/biolockj/module     ##
##  For each valid module, return the template Nextflow process code block.   ##
##  Remaining value = Java class name module.getClass().getName() after       ##
##  substituting "_" for each "." characters in the Java class name           ##
################################################################################
. /app/biolockj/script/blj_config
. "${AWS_LIB}"

# Build the template file that NextflowUtil.java will use to create the pipeline main.nf
# Param 1 - All make_nextflow script args
build_template() {
	
	modules=( ${@/${1}/} )
	echo "Building Nextflow Template ${1} with ---> ${modules}"
	modules=${modules[*]}
	numModules=$(echo $modules | wc -w | xargs)
	summaryMsg="BioLockJ $(biolockj -v) generated Nextflow Config with $numModules BioModule process definitions"
	echo "// $summaryMsg" > "${1}"
	echo "" >> "${1}"
	for module in ${modules[@]}; do
		echo "process ${module} {" >> "${1}"
		echo '    echo true' >> "${1}"
		echo '    cpus $script.numThreads' >> "${1}"
		echo '    memory $aws.ram' >> "${1}"
		echo '    label $nextflow.dockerImage' >> "${1}"
		echo '    input:' >> "${1}"
		echo '    file worker from Channel.watchPath( "BLJ_MODULE_SUB_DIR/*.sh" )' >> "${1}"
		echo '    """' >> "${1}"
		echo '    #!/bin/bash' >> "${1}"
		echo '    bash ${worker}' >> "${1}"
		echo '    """' >> "${1}"
		echo '}' >> "${1}"
	done
	echo "-----------------------------------------------------------------------------------------"
	[ -f "${1}" ] && echo "Success! -->  $summaryMsg" && echo "Deployed: ${1}" && cat "${1}" && \
		echo "-----------------------------------------------------------------------------------------"	
}

# Verify at least 2 inpur parameters
verify_inputs() {
	[ $# -lt 2 ] && \
		exit_script "Error [ make_nextflow.verify_inputs() ]: Script requires 1) main.nf file-path + 2) list of fully qualified BioModule Java class names"
	[ ! -d "$(dirname ${1})" ] && \
		exit_script "Error [ make_nextflow.verify_inputs() ]: Directory \"$(dirname ${1})\" from template nf path \"${1}\" not found!"
}

verify_inputs $@
build_template $@
