#!/bin/bash

get_blj_options() {
	echo "-D -b /Users/msioda/projects -C /Users/msioda/git/blj_support/resources/test/config/docker/local -c /config/testDockerRdp.properties -i /Users/msioda/git/blj_support/resources/test/data/r16s_fastq/R1 -m /Users/msioda/git/blj_support/resources/test/metadata"
}



docker run -e "BLJ_OPTIONS=$(get_blj_options)" \
	 -v /var/run/docker.sock:/var/run/docker.sock \
		-v /Users/msioda/projects:/pipelines:delegated \
		-v /Users/msioda/git/blj_support/resources/test/config/docker/local:/config \
		-v /Users/msioda/git/blj_support/resources/test/data/r16s_fastq/R1:/input \
		-v /Users/msioda/git/blj_support/resources/test/metadata:/meta \
		--rm -it $DOCKER_HUB_USER/blj_manager /bin/bash

