/**
 * This package contains Parser {@link biolockj.module.BioModule}s that convert the WGS taxonomy reports generated by
 * WGS classifiers (such as Kraken, Kraken2 Metaphlan2, or Humann2) into standardized OTU abundance tables.<br>
 */
package biolockj.module.implicit.parser.wgs;
