AWSTemplateFormatVersion: 2010-09-09
Description: >-
  AWS CloudFormation Template for BioLockJ Genomics pipeline using AWS Batch 
  This file only creates the roles, vpcs, and subnets necssary for deployment
  Note: this cloudformation stack requires one parameter, your public IP address
  which is automatically queried from inside the main script.  This is to only
  allow access from the user's current IP Address The other scripts pull the
  ARNs of these resources to: 1.) Create a keypair 2.) Create an AMI with
  expanded Docker storage space and miniconda 3.) setup a compute environment
  and queue Usage: CreateRolesAndComputeEnvironment.sh [arguments]
Parameters:
  NetworkAccessIP:
    Description: Source that has SSH access to the bastion host. (i.e. 50.32.108.38/32)
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: must be a valid CIDR range of the form x.x.x.x/x.
  VolumeName:
    Description: The name to be used for the EFS volume
    Type: String
    MinLength: '1'
    Default: myEFSvolume
  MountPoint:
    Description: The Linux mount point for the EFS volume
    Type: String
    MinLength: '1'
    Default: myEFSvolume
Resources:
  VPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: 'True'
      EnableDnsHostnames: 'True'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 279c1982-398d-4beb-95e9-7ea871ed3b25
  InternetGateway:
    Type: 'AWS::EC2::InternetGateway'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: ca6bdb7c-af0f-4778-8b71-0a1604d35e79
  RouteTable:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref VPC
    Metadata:
      'AWS::CloudFormation::Designer':
        id: b662ea18-3ac7-4004-95ce-2eb2557ec5dc
  VPCGatewayAttachment:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 3f4ee6b9-63bd-4b07-84f5-f82811088135
  BatchSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Security Group for Batch
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Join 
            - ''
            - - !Ref 'AWS::StackName'
              - '-batch-sg'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: b65d1864-edbd-4eb5-b161-21e04b7a9a5d
  BastionSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: SSH Access to Bastion Instance
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Join 
            - ''
            - - !Ref 'AWS::StackName'
              - '-bastion-sg'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: !Ref NetworkAccessIP
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: !Ref NetworkAccessIP
        - IpProtocol: tcp
          FromPort: '443'
          ToPort: '443'
          CidrIp: !Ref NetworkAccessIP
        - IpProtocol: tcp
          FromPort: '8080'
          ToPort: '8080'
          CidrIp: !Ref NetworkAccessIP
        - IpProtocol: icmp
          FromPort: '-1'
          ToPort: '-1'
          CidrIp: !Ref NetworkAccessIP
      SecurityGroupEgress:
        - IpProtocol: '-1'
          CidrIp: 0.0.0.0/0
    Metadata:
      'AWS::CloudFormation::Designer':
        id: c1d21c28-367b-4d9d-95d4-3c712561a79f
  BastionToBastionSecurityGroupIngressNFS:
    Type: 'AWS::EC2::SecurityGroupIngress'
    Properties:
      IpProtocol: tcp
      FromPort: '2049'
      ToPort: '2049'
      SourceSecurityGroupId: !GetAtt BastionSecurityGroup.GroupId
      GroupId: !GetAtt BastionSecurityGroup.GroupId
    Metadata:
      'AWS::CloudFormation::Designer':
        id: ddcdaa9a-8ff1-4994-90bb-86598e2ff1fd
  BatchToBastionSecurityGroupIngressNFS:
    Type: 'AWS::EC2::SecurityGroupIngress'
    Properties:
      IpProtocol: tcp
      FromPort: '2049'
      ToPort: '2049'
      SourceSecurityGroupId: !GetAtt BatchSecurityGroup.GroupId
      GroupId: !GetAtt BastionSecurityGroup.GroupId
  BastionSecurityGroupEgress:
    Type: 'AWS::EC2::SecurityGroupEgress'
    Properties:
      IpProtocol: '-1'
      CidrIp: 0.0.0.0/0
      GroupId: !GetAtt BastionSecurityGroup.GroupId
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 7ad20dce-085e-463f-9df6-283f5a7d9d3a
  Subnet1:
    Type: 'AWS::EC2::Subnet'
    Properties:
      AvailabilityZone: !Select [0, !GetAZs '']
      CidrBlock: 10.0.0.0/24
      VpcId: !Ref VPC
      MapPublicIpOnLaunch: 'True'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 87ccb9df-192a-4548-97f8-e7aa00fce39b
  Subnet2:
    Type: 'AWS::EC2::Subnet'
    Properties:
      AvailabilityZone: !Select [1, !GetAZs '']
      CidrBlock: 10.0.1.0/24
      VpcId: !Ref VPC
      MapPublicIpOnLaunch: 'True'
  NetworkInterfaces:
    Type: 'AWS::EC2::NetworkInterface'
    Properties:
      Description: "Network interface for Bastion Node"
      SubnetId: !Ref Subnet1
      GroupSet:
        - Ref: BatchSecurityGroup
        - Ref: BastionSecurityGroup
  Route:
    Type: 'AWS::EC2::Route'
    Properties:
      RouteTableId: !Ref RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 37fc803d-6834-41a9-b4f7-4bc4d978d40f
  SubnetRouteTableAssociation1:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      RouteTableId: !Ref RouteTable
      SubnetId: !Ref Subnet1
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 63060ecd-552e-4088-a4eb-e152be2eaa9c
  SubnetRouteTableAssociation2:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      RouteTableId: !Ref RouteTable
      SubnetId: !Ref Subnet2
  BatchServiceRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: batch.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSBatchServiceRole'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 99df7c09-9e3f-4047-9b86-abd8dbcb30cd
  IamInstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Roles:
        - !Ref EcsInstanceRole
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 6cad450f-0404-4ce6-b741-ff9bcdc396ae
  ECSTaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "ecs-tasks.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
      - "arn:aws:iam::aws:policy/AmazonS3FullAccess"
      - "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy"
      - "arn:aws:iam::aws:policy/AmazonElasticFileSystemFullAccess"
      - "arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceforEC2Role"
      - "arn:aws:iam::aws:policy/service-role/AmazonEC2RoleForSSM"
      - "arn:aws:iam::aws:policy/AmazonEC2FullAccess"
  EcsInstanceRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2008-10-17
        Statement:
          - Sid: ''
            Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonEC2FullAccess'
        - 'arn:aws:iam::aws:policy/AmazonS3FullAccess'
        - 'arn:aws:iam::aws:policy/AmazonElasticFileSystemFullAccess'
        - >-
          arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceforEC2Role
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 05ba0cf7-2248-40b5-bf47-a3b5f0330854
  SpotIamFleetRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: ''
            Effect: Allow
            Principal:
              Service: spotfleet.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AmazonEC2SpotFleetRole'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 4d9dff45-f244-46b4-bc94-72252bc75793
  FileSystem:
    Type: 'AWS::EFS::FileSystem'
    Properties:
      PerformanceMode: maxIO
      FileSystemTags:
        - Key: Name
          Value: !Join [ "-", [ !Ref "AWS::StackName", EFS-shared ] ]
    Metadata:
      'AWS::CloudFormation::Designer':
        id: e3143b62-7cb1-4dea-87cd-5e0f290e684b
  MountTarget1:
    Type: 'AWS::EFS::MountTarget'
    Properties:
      FileSystemId:
        Ref: FileSystem
      SubnetId:
        Ref: Subnet1
      SecurityGroups:
        - Ref: BastionSecurityGroup
        - Ref: BatchSecurityGroup
  MountTarget2:
    Type: 'AWS::EFS::MountTarget'
    Properties:
      FileSystemId:
        Ref: FileSystem
      SubnetId:
        Ref: Subnet2
      SecurityGroups:
        - Ref: BastionSecurityGroup
        - Ref: BatchSecurityGroup
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 6a0a382e-57d1-4fa4-944d-fe8dcbebb648
  HeadNodeLaunchTemplate:
    Type: "AWS::EC2::LaunchTemplate"
    Properties:
      LaunchTemplateName: !Join [ "-", [ !Ref "AWS::StackName", "HeadNodeTemplateWithEFS" ] ]
      LaunchTemplateData:
        UserData:
          Fn::Base64: !Sub |
            MIME-Version: 1.0
            Content-Type: multipart/mixed; boundary="==MYBOUNDARY=="
            
            --==MYBOUNDARY==
            Content-Type: text/cloud-config; charset="us-ascii"
            
            package_update: true

            packages:
            - amazon-efs-utils
            
            runcmd:
            - yum update -y
            - file_system_id_01=${FileSystem}
            - efs_directory=/mnt/efs
            - mkdir -p ${!efs_directory}
            - echo "${!file_system_id_01}:/ ${!efs_directory} efs defaults,_netdev" >> /etc/fstab
            - mount -a -t efs defaults
            - chown -R ec2-user:ec2-user ${!efs_directory}
            
            --==MYBOUNDARY==--
    Metadata:
      'AWS::CloudFormation::Designer':
        id: a2cdae54-64a6-41d6-8565-9eadf5bef1bc
  BatchNodeLaunchTemplate:
    Type: "AWS::EC2::LaunchTemplate"
    Properties:
      LaunchTemplateName: !Join [ "-", [ !Ref "AWS::StackName", "BatchNodeTemplateWithEFS" ] ]
      LaunchTemplateData:
        UserData:
          Fn::Base64: !Sub |
            MIME-Version: 1.0
            Content-Type: multipart/mixed; boundary="==MYBOUNDARY=="
            
            --==MYBOUNDARY==
            Content-Type: text/cloud-config; charset="us-ascii"
            
            packages:
            - amazon-efs-utils
            
            runcmd:
            - file_system_id_01=${FileSystem}
            - efs_directory=/mnt/efs
            - mkdir -p ${!efs_directory}
            - echo "${!file_system_id_01}:/ ${!efs_directory} efs defaults,_netdev" >> /etc/fstab
            - mount -a -t efs defaults
            - chown -R ec2-user:ec2-user ${!efs_directory}
            
            --==MYBOUNDARY==--
    Metadata:
      'AWS::CloudFormation::Designer':
        id: a2cdae54-64a6-41d6-8565-9eadf5bef1bc

Outputs:
  Subnet1:
    Value: !Ref Subnet1
  Subnet2:
    Value: !Ref Subnet2
  BatchSecurityGroup:
    Value: !Ref BatchSecurityGroup
  BastionSecurityGroup:
    Value: !Ref BastionSecurityGroup
  ECSTaskRole:
    Value: !Ref ECSTaskRole
  EcsInstanceRoleArn:
    Value: !Ref EcsInstanceRole
  IamInstanceProfileArn:
    Value: !Ref IamInstanceProfile
  SpotIamFleetRoleArn:
    Value: !Ref SpotIamFleetRole
  BatchServiceRoleArn:
    Value: !Ref BatchServiceRole
  FileSystemId:
    Value: !Ref FileSystem
  HeadNodeLaunchTemplateId:
    Value: !Ref HeadNodeLaunchTemplate
  BatchNodeLaunchTemplateId:
    Value: !Ref BatchNodeLaunchTemplate
Metadata:
  'AWS::CloudFormation::Designer':
    4d9dff45-f244-46b4-bc94-72252bc75793:
      size:
        width: 60
        height: 60
      position:
        x: 210
        'y': 510
      z: 1
      embeds: []
    05ba0cf7-2248-40b5-bf47-a3b5f0330854:
      size:
        width: 60
        height: 60
      position:
        x: 300
        'y': 510
      z: 1
      embeds: []
    6cad450f-0404-4ce6-b741-ff9bcdc396ae:
      size:
        width: 60
        height: 60
      position:
        x: 390
        'y': 510
      z: 1
      embeds: []
      isassociatedwith:
        - 05ba0cf7-2248-40b5-bf47-a3b5f0330854
    99df7c09-9e3f-4047-9b86-abd8dbcb30cd:
      size:
        width: 60
        height: 60
      position:
        x: 480
        'y': 510
      z: 1
      embeds: []
    ca6bdb7c-af0f-4778-8b71-0a1604d35e79:
      size:
        width: 60
        height: 60
      position:
        x: 790
        'y': 60
      z: 0
      embeds: []
    279c1982-398d-4beb-95e9-7ea871ed3b25:
      size:
        width: 1170
        height: 720
      position:
        x: 90
        'y': 90
      z: 1
      embeds:
        - e3143b62-7cb1-4dea-87cd-5e0f290e684b
        - a2cdae54-64a6-41d6-8565-9eadf5bef1bc
        - 87ccb9df-192a-4548-97f8-e7aa00fce39b
        - c1d21c28-367b-4d9d-95d4-3c712561a79f
        - b65d1864-edbd-4eb5-b161-21e04b7a9a5d
        - b662ea18-3ac7-4004-95ce-2eb2557ec5dc
    87ccb9df-192a-4548-97f8-e7aa00fce39b:
      size:
        width: 240
        height: 240
      position:
        x: 420
        'y': 150
      z: 2
      parent: 279c1982-398d-4beb-95e9-7ea871ed3b25
      embeds:
        - 6a0a382e-57d1-4fa4-944d-fe8dcbebb648
      iscontainedinside:
        - 279c1982-398d-4beb-95e9-7ea871ed3b25
        - 279c1982-398d-4beb-95e9-7ea871ed3b25
        - 279c1982-398d-4beb-95e9-7ea871ed3b25
        - 279c1982-398d-4beb-95e9-7ea871ed3b25
        - 279c1982-398d-4beb-95e9-7ea871ed3b25
        - 279c1982-398d-4beb-95e9-7ea871ed3b25
        - 279c1982-398d-4beb-95e9-7ea871ed3b25
        - 279c1982-398d-4beb-95e9-7ea871ed3b25
        - 279c1982-398d-4beb-95e9-7ea871ed3b25
        - 279c1982-398d-4beb-95e9-7ea871ed3b25
        - 279c1982-398d-4beb-95e9-7ea871ed3b25
        - 279c1982-398d-4beb-95e9-7ea871ed3b25
        - 279c1982-398d-4beb-95e9-7ea871ed3b25
        - 279c1982-398d-4beb-95e9-7ea871ed3b25
    b65d1864-edbd-4eb5-b161-21e04b7a9a5d:
      size:
        width: 60
        height: 60
      position:
        x: 480
        'y': 330
      z: 2
      parent: 279c1982-398d-4beb-95e9-7ea871ed3b25
      embeds: []
      iscontainedinside:
        - 279c1982-398d-4beb-95e9-7ea871ed3b25
        - 279c1982-398d-4beb-95e9-7ea871ed3b25
        - 279c1982-398d-4beb-95e9-7ea871ed3b25
        - 279c1982-398d-4beb-95e9-7ea871ed3b25
        - 279c1982-398d-4beb-95e9-7ea871ed3b25
        - 279c1982-398d-4beb-95e9-7ea871ed3b25
        - 279c1982-398d-4beb-95e9-7ea871ed3b25
        - 279c1982-398d-4beb-95e9-7ea871ed3b25
        - 279c1982-398d-4beb-95e9-7ea871ed3b25
        - 279c1982-398d-4beb-95e9-7ea871ed3b25
        - 279c1982-398d-4beb-95e9-7ea871ed3b25
        - 279c1982-398d-4beb-95e9-7ea871ed3b25
        - 279c1982-398d-4beb-95e9-7ea871ed3b25
        - 279c1982-398d-4beb-95e9-7ea871ed3b25
    3f4ee6b9-63bd-4b07-84f5-f82811088135:
      source:
        id: 279c1982-398d-4beb-95e9-7ea871ed3b25
      target:
        id: ca6bdb7c-af0f-4778-8b71-0a1604d35e79
      z: 1
    b662ea18-3ac7-4004-95ce-2eb2557ec5dc:
      size:
        width: 510
        height: 330
      position:
        x: 120
        'y': 150
      z: 2
      parent: 279c1982-398d-4beb-95e9-7ea871ed3b25
      embeds:
        - 37fc803d-6834-41a9-b4f7-4bc4d978d40f
      iscontainedinside:
        - 279c1982-398d-4beb-95e9-7ea871ed3b25
        - 279c1982-398d-4beb-95e9-7ea871ed3b25
        - 279c1982-398d-4beb-95e9-7ea871ed3b25
        - 279c1982-398d-4beb-95e9-7ea871ed3b25
        - 279c1982-398d-4beb-95e9-7ea871ed3b25
        - 279c1982-398d-4beb-95e9-7ea871ed3b25
        - 279c1982-398d-4beb-95e9-7ea871ed3b25
        - 279c1982-398d-4beb-95e9-7ea871ed3b25
        - 279c1982-398d-4beb-95e9-7ea871ed3b25
        - 279c1982-398d-4beb-95e9-7ea871ed3b25
        - 279c1982-398d-4beb-95e9-7ea871ed3b25
        - 279c1982-398d-4beb-95e9-7ea871ed3b25
        - 279c1982-398d-4beb-95e9-7ea871ed3b25
        - 279c1982-398d-4beb-95e9-7ea871ed3b25
    63060ecd-552e-4088-a4eb-e152be2eaa9c:
      source:
        id: b662ea18-3ac7-4004-95ce-2eb2557ec5dc
      target:
        id: 87ccb9df-192a-4548-97f8-e7aa00fce39b
      z: 2
    37fc803d-6834-41a9-b4f7-4bc4d978d40f:
      size:
        width: 60
        height: 60
      position:
        x: 300
        'y': 150
      z: 3
      parent: b662ea18-3ac7-4004-95ce-2eb2557ec5dc
      embeds: []
      isassociatedwith:
        - ca6bdb7c-af0f-4778-8b71-0a1604d35e79
      iscontainedinside:
        - b662ea18-3ac7-4004-95ce-2eb2557ec5dc
        - b662ea18-3ac7-4004-95ce-2eb2557ec5dc
        - b662ea18-3ac7-4004-95ce-2eb2557ec5dc
        - b662ea18-3ac7-4004-95ce-2eb2557ec5dc
        - b662ea18-3ac7-4004-95ce-2eb2557ec5dc
        - b662ea18-3ac7-4004-95ce-2eb2557ec5dc
        - b662ea18-3ac7-4004-95ce-2eb2557ec5dc
        - b662ea18-3ac7-4004-95ce-2eb2557ec5dc
        - b662ea18-3ac7-4004-95ce-2eb2557ec5dc
        - b662ea18-3ac7-4004-95ce-2eb2557ec5dc
        - b662ea18-3ac7-4004-95ce-2eb2557ec5dc
        - b662ea18-3ac7-4004-95ce-2eb2557ec5dc
        - b662ea18-3ac7-4004-95ce-2eb2557ec5dc
        - b662ea18-3ac7-4004-95ce-2eb2557ec5dc
    7ad20dce-085e-463f-9df6-283f5a7d9d3a:
      source:
        id: c1d21c28-367b-4d9d-95d4-3c712561a79f
      target:
        id: c1d21c28-367b-4d9d-95d4-3c712561a79f
      z: 2
    e3143b62-7cb1-4dea-87cd-5e0f290e684b:
      size:
        width: 60
        height: 60
      position:
        x: 150
        'y': 510
      z: 2
      parent: 279c1982-398d-4beb-95e9-7ea871ed3b25
      embeds: []
    c1d21c28-367b-4d9d-95d4-3c712561a79f:
      size:
        width: 60
        height: 60
      position:
        x: 690
        'y': 150
      z: 2
      parent: 279c1982-398d-4beb-95e9-7ea871ed3b25
      embeds: []
      iscontainedinside:
        - 279c1982-398d-4beb-95e9-7ea871ed3b25
        - 279c1982-398d-4beb-95e9-7ea871ed3b25
        - 279c1982-398d-4beb-95e9-7ea871ed3b25
        - 279c1982-398d-4beb-95e9-7ea871ed3b25
        - 279c1982-398d-4beb-95e9-7ea871ed3b25
    ddcdaa9a-8ff1-4994-90bb-86598e2ff1fd:
      source:
        id: c1d21c28-367b-4d9d-95d4-3c712561a79f
      target:
        id: c1d21c28-367b-4d9d-95d4-3c712561a79f
      z: 2
    6a0a382e-57d1-4fa4-944d-fe8dcbebb648:
      size:
        width: 60
        height: 60
      position:
        x: 540
        'y': 180
      z: 3
      parent: 87ccb9df-192a-4548-97f8-e7aa00fce39b
      embeds: []
      isassociatedwith:
        - e3143b62-7cb1-4dea-87cd-5e0f290e684b
        - b65d1864-edbd-4eb5-b161-21e04b7a9a5d
        - c1d21c28-367b-4d9d-95d4-3c712561a79f
      iscontainedinside:
        - 87ccb9df-192a-4548-97f8-e7aa00fce39b
        - 87ccb9df-192a-4548-97f8-e7aa00fce39b
        - 87ccb9df-192a-4548-97f8-e7aa00fce39b
        - 87ccb9df-192a-4548-97f8-e7aa00fce39b
        - 87ccb9df-192a-4548-97f8-e7aa00fce39b
    a2cdae54-64a6-41d6-8565-9eadf5bef1bc:
      size:
        width: 60
        height: 60
      position:
        x: 160
        'y': 710
      z: 2
      parent: 279c1982-398d-4beb-95e9-7ea871ed3b25
      embeds: []
      iscontainedinside:
        - 279c1982-398d-4beb-95e9-7ea871ed3b25
        - 279c1982-398d-4beb-95e9-7ea871ed3b25
