/**
 * This package contains Parser {@link biolockj.module.BioModule}s that convert the 16S taxonomy reports generated by
 * 16S classifiers (such as RDP and QIIME) into standardized OTU abundance tables.<br>
 */
package biolockj.module.implicit.parser.r16s;
